config/routes.rb
Loomio::Application.routes.draw do

  slug_regex = /[a-z0-9\-\_]*/i
  ActiveAdmin.routes(self)

  namespace :admin do
    resource :email_groups, only: [:create, :new]
    resources :stats, only: [] do
      collection do
        get :events
      end
    end
  end

  get "/explore", to: 'explore#index', as: :explore
  get "/explore/search", to: "explore#search", as: :search_explore
  get "/explore/category/:id", to: "explore#category", as: :category_explore

  get "/groups", to: 'public_groups#index', as: :public_groups

  get "/new_group", to: 'groups#new'

  resource :search, only: :show

  devise_for :users, controllers: { sessions: 'users/sessions',
                                    registrations: 'users/registrations',
                                    omniauth_callbacks: 'users/omniauth_callbacks' }

  namespace :inbox do
    get   '/', action: 'index'
    get   'size'
    get   'preferences'
    put   'update_preferences'
    match 'mark_as_read'
    match 'mark_all_as_read/:id', action: 'mark_all_as_read', as: :mark_all_as_read
    match 'unfollow'
  end

  resources :group_requests, only: [:create, :new] do
    get :confirmation, on: :collection
  end

  resources :invitations, only: [:show, :create, :destroy]

  resources :groups, path: 'g', only: [:create, :edit] do
    scope module: :groups do
      resources :memberships, only: [:index, :destroy, :new, :create] do
        member do
         post :make_admin
         post :remove_admin
        end
      end
      resource :subscription, controller: 'subscriptions', only: [:new, :show] do
        collection do
          post :checkout
          get :confirm
          get :payment_failed
        end
      end
      scope controller: 'group_setup' do
        member do
          get :setup
          put :finish
        end
      end

      get :ask_to_join, controller: 'membership_requests', action: :new
      resources :membership_requests, only: [:create]
      get :membership_requests,  to: 'manage_membership_requests#index', as: 'membership_requests'
    end

    member do
      post :add_members
      post :hide_next_steps
      get :add_subgroup
      post :email_members
      post :edit_description
      delete :leave_group
      get :members_autocomplete
    end

    resources :motions,     only: [:index]
    resources :discussions, only: [:index, :new]
    resources :invitations, only: [:new, :destroy]
  end

  scope module: :groups, path: 'g', slug: slug_regex do
    get    ':id(/:slug)', action: 'show', as: :group
    put    ':id(/:slug)', action: 'update'
    delete ':id(/:slug)', action: 'destroy'

    post 'archive/:id',  action: 'archive', as: :archive_group
  end

  scope module: :groups do
    resources :manage_membership_requests, only: [], as: 'membership_requests' do
      member do
        post :approve
        post :ignore
      end
    end
  end
  delete 'membership_requests/:id/cancel', to: 'groups/membership_requests#cancel', as: :cancel_membership_request

  resources :motions, path: 'm', only: [:new, :create, :edit, :index] do
    resources :votes, only: [:new, :create, :update]
    member do
      put :close
      put :create_outcome
      post :update_outcome
      put :edit_close_date
    end
  end

  scope module: :motions, path: 'm', slug: slug_regex do
    get    ':id(/:slug)', action: 'show', as: :motion
    put    ':id(/:slug)', action: 'update'
    delete ':id(/:slug)', action: 'destroy'
  end

  resources :discussions, path: 'd', only: [:new, :edit, :create] do
    get :activity_counts, on: :collection
    resources :invitations, only: [:new]

    member do
      post :update_description
      post :update
      post :add_comment
      post :show_description_history
      get :new_proposal
      post :move
    end
  end

  scope module: :discussions, path: 'd', slug: slug_regex do
    get    ':id(/:slug)', action: 'show',    as: :discussion
    put    ':id(/:slug)', action: 'update'
    delete ':id(/:slug)', action: 'destroy'

    post ':id/preview_version/(:version_id)', action: 'preview_version', as: 'preview_version_discussion'
    post 'update_version/:version_id',        action: 'update_version',   as: 'update_version_discussion'
  end

  resources :comments , only: :destroy do
    post :like, on: :member
    post :translate, on: :member
  end

  resources :attachments, only: [:create, :new] do
    collection do
      get 'sign'
      get :iframe_upload_result
    end
  end

  resources :notifications, :only => :index do
    collection do
      get :groups_tree_dropdown
      get :dropdown_items
      post :mark_as_viewed
    end
  end

  resources :users, path: 'u', only: [:new] do
    member do
      put :set_avatar_kind
      post :upload_new_avatar
    end
  end

  scope module: :users do
    match '/profile',          action: 'profile', as: :profile
    scope module: :email_preferences do
      get '/email_preferences', action: 'edit',   as: :email_preferences
      put '/email_preferences', action: 'update', as: :update_email_preferences
    end
  end

  scope module: :users, path: 'u' do
    get ':id(/:slug)', action: 'show',    slug: slug_regex, as: :user
    put ':id(/:slug)', action: 'update',  slug: slug_regex
  end

  match '/announcements/:id/hide', to: 'announcements#hide', as: 'hide_announcement'

  get '/users/invitation/accept' => redirect {|params, request|  "/invitations/#{request.query_string.gsub('invitation_token=','')}"}
  get '/group_requests/:id/start_new_group' => redirect {|params, request|  "/invitations/#{request.query_string.gsub('token=','')}"}

  get '/contributions' => redirect('/crowd')
  get '/contributions/thanks' => redirect('/crowd')
  get '/contributions/callback' => redirect('/crowd')
  get '/crowd' => redirect('https://love.loomio.org/')

  # resources :contributions, only: [:index, :create] do
  #   get :callback, on: :collection
  #   get :thanks, on: :collection
  # end

  get '/dashboard', to: 'dashboard#show', as: 'dashboard'
  root :to => 'marketing#index'

  scope controller: 'pages' do
    get :about
    get :privacy
    get :purpose
    get :services
    get :terms_of_service
    get :third_parties
    get :wallets
    get :browser_not_supported
  end

  scope controller: 'campaigns' do
    get :hide_crowdfunding_banner
  end

  scope controller: 'help' do
    get :help
  end

  get '/detect_locale' => 'detect_locale#show'
  match '/detect_video_locale' => 'detect_locale#video', as: :detect_video_locale

  resources :contact_messages, only: [:new, :create]
  match 'contact(/:destination)', to: 'contact_messages#new'

  #redirect from wall to new group signup
  namespace :group_requests do
    get 'selection', action: 'new'
    get 'subscription', action: 'new'
    get 'pwyc', action: 'new'
  end

  #redirect old invites
  match "/groups/:id/invitations/:token" => "group_requests#start_new_group"

  #redirect old pages:
  get '/we_the_people' => redirect('/')
  get '/collaborate'   => redirect('/')
  get '/woc'           => redirect('/')
  get '/discussions/:id', to: 'discussions_redirect#show'
  get '/groups/:id',      to: 'groups_redirect#show'
  get '/motions/:id',     to: 'motions_redirect#show'

  scope path: 'pages' do
    get 'home'         => redirect('/')
    get 'how*it*works' => redirect('/purpose#how-it-works')
    get 'get*involved' => redirect('/about')
    get 'privacy'      => redirect('/privacy_policy')
    get 'about'        => redirect('/about#about-us')
    match 'contact'    => 'contact_messages#new'
  end

  get '/get*involved'       => redirect('/purpose#how-it-works')
  get '/how*it*works'       => redirect('/purpose#how-it-works')
  get '/about#how-it-works' => redirect('/purpose#how-it-works')

  get '/blog'       => redirect('http://blog.loomio.org')
  get '/press'      => redirect('http://blog.loomio.org/press-pack')
  get '/press-pack' => redirect('http://blog.loomio.org/press-pack')
end

app/controllers/discussions_controller.rb
class DiscussionsController < GroupBaseController
  include DiscussionsHelper

  before_filter :authenticate_user!, :except => [:show, :index]
  before_filter :load_resource_by_key, except: [:new, :create, :index, :update_version]
  authorize_resource :except => [:new, :create, :index, :add_comment]

  after_filter :mark_as_read, only: :show

  caches_action :show, :cache_path => Proc.new { |c| c.params }, unless: :user_signed_in?, :expires_in => 5.minutes

  rescue_from ActiveRecord::RecordNotFound do
    render 'application/display_error', locals: { message: t('error.not_found') }
  end

  def new
    @discussion = Discussion.new
    @discussion.uses_markdown = current_user.uses_markdown
    @group = Group.find_by_id params[:group_id]
    @discussion.group = @group
    @user_groups = current_user.groups.order('name')
  end

  def edit
  end

  def update
    if DiscussionService.edit_discussion(current_user, permitted_params.discussion, @discussion)
      flash[:notice] = 'Discussion was successfully updated.'
      redirect_to @discussion
    else
      @user_groups = current_user.groups.order('name')
      render :edit
    end
  end

  def create
    build_discussion
    if DiscussionService.start_discussion(@discussion)
      flash[:success] = t("success.discussion_created")
      redirect_to @discussion
    else
      render action: :new
      flash[:error] = t("error.discussion_not_created")
    end
  end

  def destroy
    @discussion.delayed_destroy
    flash[:success] = t("success.discussion_deleted")
    redirect_to @discussion.group
  end

  def index
    if params[:group_id].present?
      @group = Group.find(params[:group_id])
      if cannot? :show, @group
        head 401
      else
        @no_discussions_exist = (@group.discussions.count == 0)
        @discussions = GroupDiscussionsViewer.
                       for(group: @group, user: current_user).
                       without_open_motions.
                       order_by_latest_comment.
                       page(params[:page]).per(10)
      end
    else
      authenticate_user!
      @no_discussions_exist = (current_user.discussions.count == 0)
      @discussions = Queries::VisibleDiscussions.
                     new(user: current_user).
                     without_open_motions.
                     order_by_latest_comment.
                     page(params[:page]).per(10)
    end
  end

  def show
    @group = GroupDecorator.new(@discussion.group)

    if params[:proposal]
      @motion = @discussion.motions.find(params[:proposal])
    else
      @motion = @discussion.most_recent_motion
    end

    if @motion
      @motion_reader = MotionReader.for(user: current_user_or_visitor, motion: @motion)
    end

    @discussion_reader = DiscussionReader.for(user: current_user_or_visitor, discussion: @discussion)

    @closed_motions = @discussion.closed_motions

    @uses_markdown = current_user_or_visitor.uses_markdown?

    @activity = @discussion.activity.page(requested_or_first_unread_page).per(Discussion::PER_PAGE)
    assign_meta_data
  end

  def move
    destination_group = Group.find params[:destination_group_id]

    discussion_mover = MoveDiscussionService.new(discussion: @discussion,
                                                 destination_group: destination_group,
                                                 user: current_user)
    if discussion_mover.move!
      flash[:notice] = t(:'success.discussion_moved', group_name: destination_group.name)
    else
      flash[:alert] = t(:'error.discussion_not_moved', group_name: destination_group.name)
    end

    redirect_to @discussion
  end

  def add_comment
    build_comment
    if DiscussionService.add_comment(@comment)
      current_user.update_attributes(uses_markdown: params[:uses_markdown])
      DiscussionReader.for(user: current_user, discussion: @discussion).viewed!
    else
      head :ok and return
    end
  end

  def new_proposal
    if @discussion.current_motion
      redirect_to @discussion
      flash[:notice] = "A current proposal already exists for this disscussion."
    else
      @motion = Motion.new
      @motion.discussion = @discussion
      @group = GroupDecorator.new(@discussion.group)
      render 'motions/new'
    end
  end

  def update_description
    @discussion.set_description!(params[:description], params[:description_uses_markdown], current_user)
    redirect_to @discussion
  end

  def edit_title
    @discussion.set_title!(params.require(:title), current_user)
    redirect_to @discussion
  end

  def show_description_history
    @originator = User.find @discussion.originator.to_i
    respond_to do |format|
      format.js
    end
  end

  def preview_version
    # assign live item if no version_id is passed
    if params[:version_id].present?
      version = Version.find(params[:version_id])
      @discussion = version.reify
    end
    @originator = User.find @discussion.originator.to_i
    respond_to do |format|
      format.js { render :action => 'show_description_history' }
    end
  end

  def update_version
    @version = Version.find(params[:version_id])
    @version.reify.save!
    redirect_to @version.reify()
  end

  private

  def load_resource_by_key
    @discussion ||= Discussion.published.find_by_key!(params[:id])
  end

  def build_comment
    @comment = Comment.new(body: params[:comment],
                           uses_markdown: params[:uses_markdown])

    attachment_ids = Array(params[:attachments]).map(&:to_i)

    @comment.discussion = @discussion
    @comment.author = current_user
    @comment.attachment_ids = attachment_ids
    @comment.attachments_count = attachment_ids.size
    @comment
  end

  def build_discussion
    @discussion = Discussion.new(permitted_params.discussion)
    @discussion.author = current_user
  end

  def mark_as_read
    if @activity and @activity.last
      @discussion_reader.viewed!(@activity.last.updated_at)
      @motion_reader.viewed! if @motion_reader
    end
  end

  def assign_meta_data
    if @group.privacy == 'public'
      @meta_title = @discussion.title
      @meta_description = @discussion.description
    end
  end

  def group
    @group ||= find_group
  end

  def find_group
    if (params[:id] && (params[:id] != "new"))
      Discussion.published.find(params[:id]).group
    elsif params[:discussion][:group_id]
      Group.find(params[:discussion][:group_id])
    end
  end
end

app/helpers/discussions_helper.rb
module DiscussionsHelper
  include Twitter::Extractor
  include Twitter::Autolink

  def no_discussions_available?
    (@discussion_readers_with_open_motions.size + @discussion_readers_without_open_motions.size) == 0
  end

  def enough_activity_for_jump_link?
    @discussion.items_count > 3
  end

  def path_of_latest_activity
    if current_page == @discussion_reader.first_unread_page
      '#latest-activity'.html_safe
    else
      discussion_path(@discussion, page: @discussion_reader.first_unread_page, anchor: 'latest-activity')
    end
  end

  def path_of_add_comment
    if current_page == @discussion_reader.first_unread_page
      '#comment-input'
    else
      if actual_total_pages == 1
        discussion_path(@discussion, anchor: 'comment-input')
      else
        discussion_path(@discussion, page: actual_total_pages, anchor: 'comment-input')
      end
    end
  end

  def css_classes_for_discussion_preview(discussion, discussion_reader)
    class_names = []
    class_names << 'showing-group' unless @group == discussion.group
    class_names << 'unread' if discussion_reader.unread_content_exists?
    class_names.join(' ')
  end

  def add_mention_links(comment)
    auto_link_usernames_or_lists(comment, :username_url_base => "#", :username_include_symbol => true)
  end

  def css_for_markdown_link(target, setting)
    return "icon-ok" if (target.uses_markdown == setting)
  end

  def markdown_img(uses_markdown)
    if uses_markdown
      image_tag("markdown_on.png", class: 'markdown-icon markdown-on')
    else
      image_tag("markdown_off.png", class: 'markdown-icon markdown-off')
    end
  end

  def last_page?
    actual_total_pages == current_page
  end

  def actual_total_pages
    if @activity.total_pages == 0
      1
    else
      @activity.total_pages
    end
  end

  def current_page
    @current_page ||= requested_or_first_unread_page
  end

  def requested_or_first_unread_page
    if params[:page]
      params[:page].to_i
    else
      @discussion_reader.first_unread_page
    end
  end

  def user_has_not_read_event?(event)
    if @discussion_reader.last_read_at.present?
      if event.belongs_to?(current_user)
        false
      else
        @discussion_reader.last_read_at < event.updated_at
      end
    else
      false
    end
  end

  def discussion_privacy_options(discussion)
    options = []
    group =
      if discussion.group_id
        t(:'simple_form.labels.discussion.of') + discussion.group.name
      else
        t :'simple_form.labels.discussion.of_no_group'
      end
    icon =
    header = t "simple_form.labels.discussion.privacy_public_header"
    description = t 'simple_form.labels.discussion.privacy_public_description'
    options << ["<span class='discussion-privacy-setting-header'><i class='fa fa-globe'></i>#{header}<br /><p>#{description}</p>".html_safe, false]

    header = t "simple_form.labels.discussion.privacy_private_header"
    description = t(:'simple_form.labels.discussion.privacy_private_description', group: group)
    options << ["<span class='discussion-privacy-setting-header'><i class='fa fa-lock'></i>#{header}<br /><p>#{description}</p>".html_safe, true ]
  end

  def current_language
    Translation.language I18n.locale.to_s
  end

  def privacy_language(discussion)
    discussion.private? ? "private" : "public"
  end

  def privacy_icon(discussion)
    discussion.private? ? "lock" : "globe"
  end
end

app/views/discussions/_activity.html.haml
%ul#activity-list
  .top-pagination
    = link_to_previous_page items, "Show earlier comments"

  -marked_first_unread = false
  - items.each do |event|
    - next if event.kind == 'new_discussion'
    -unless @discussion_reader.first_read?
      - unless marked_first_unread
        - unless @discussion_reader.has_read?(event)
          - unless event.belongs_to? current_user_or_visitor
            - marked_first_unread = true
            .shifted_anchor#latest-activity
            .dog-ear#js-dog-ear
              &nbsp;
            .new-activity-divider

    %li.activity-item-container
      - if event.kind == 'new_comment'
        = render event.eventable
      - else
        - discussion_item = DiscussionItem.new(event)
        = render 'discussion_item', :item => discussion_item

app/views/discussions/_add_comment.html.haml
- if last_page?
  - if can? :add_comment, discussion
    = form_tag add_comment_discussion_path(discussion), :remote => true, id: "new-comment-form" do
      = render 'avatar', user: current_user
      #comment-input{ data: {group: @group.id, autocomplete_path: members_autocomplete_group_path(@group) } }
        .form-container
          = text_area_tag 'comment', "", id: 'new-comment', class: 'js-warn-before-navigating-away', placeholder: t(:comment_form_placeholder)
          #attachment-container

        = hidden_field_tag 'uses_markdown', @uses_markdown, {id: 'global-uses-markdown'}
        = submit_tag t(:comment_form_submit_button), class: "btn btn-small submit", id: 'post-new-comment', :data => {:disable_with => t(:comment_form_submit_button)}
      .comment-toolbar
        -unless browser.ie? && browser.version.to_i < 10
          .attachment-icon#add-attachment-icon
        .dropdown#comment-markdown-dropdown.global-markdown-setting
          %a.dropdown-toggle{href:'#comment-markdown-dropdown', id:'comment-markdown-dropdown-link', 'data-toggle'=> 'dropdown'}
            = markdown_img(@uses_markdown)
          = render 'markdown_setting', target: current_user

    -unless browser.ie? && browser.version.to_i < 10
      = s3_uploader_form post: attachments_url, as: "attachment[location]", redirect_url: iframe_upload_result_attachments_url do
        = file_field_tag :file, multiple: true

      %script#template-upload-in-progress{type: "text/x-tmpl"}
        .attachment-uploader
          .uploading-filename
            {%=o.name%}
          %button.close.cancel-upload &times;
          .progress.active
            .bar

      %script#template-upload--attached{type: "text/x-tmpl"}
        .attachments
          .attachment-success{data: { 'attachment-id' => "{%=o.id%}" } }
            = link_to "{%=o.name%}", "{%=o.location%}", target: "_blank"
            ({%= (parseInt(o.size) / (1024*1024)).toFixed(2) + " MB" %})
            %button.close.remove-attachment &times;

      %script#template-upload--comment-input{type: "text/x-tmpl"}
        %input{type: 'hidden', name: "attachments[]", value: '{%=o.id%}', data: { 'attachment-id' => "{%=o.id%}" }}

  - else
    = render "add_comment_placeholder"

app/views/discussions/_description.html.haml
.description-container
  .description-body
    .long-description
      = render_rich_text(description, description_markdown_setting)

    - if can? :update_description, discussion
      = link_to t(:edit_discussion_context), "#", class: "edit-description edit-discussion-description bottom-panel-link", id: 'edit_description'

  - if can? :update_description, discussion
    = form_tag update_description_discussion_path(discussion), :id => "description-edit-form", :class => "hidden" do |f|
      = hidden_field_tag 'id'
      = hidden_field_tag 'description_uses_markdown', description_markdown_setting, {id: 'description-markdown-setting'}
      .control-group
        = text_area_tag 'description', description, {id: 'description-input', class: 'js-warn-before-navigating-away',  :autofocus => true }
      .save-buttons.clearfix
        = submit_tag t(:save), class: 'btn btn-small btn-grey run-validations', id: 'add-description-submit', :data => {:disable_with => t(:saving)}
        = link_to t(:cancel), "#", id: 'cancel-add-description'
        .dropdown#discussion-markdown-dropdown.local-markdown-setting
          %a.dropdown-toggle{href:'#discussion-markdown-dropdown', id:'discussion-markdown-dropdown-link', 'data-toggle'=> 'dropdown'}
            = markdown_img(description_markdown_setting)
          = render 'markdown_setting', target: discussion

app/views/discussions/_description_history.html.haml
.modal-header
  %button.close{"data-dismiss" => "modal"}×
  %h2= t "description_history.header"
.modal-body
  .revision-title
    %h3= @discussion.title
    %p
      = t("description_history.edited_by", when: time_ago_in_words(@discussion.last_versioned_at), who: @originator.name)
      %em
        = " "
        -if @discussion.live?
          =t "description_history.current"
        -else
          =link_to t("description_history.restore"), update_version_discussion_path(@discussion.version), :method => :post, :class => "", :id => "revert-to-version", :data => { :disable_with => t("description_history.applying_changes") }
  .revision-version
    %h3= t "description_history.subheader"
    %p
      -if @discussion.has_previous_versions?
        =link_to t("description_history.previous"), preview_version_discussion_path(@discussion, @discussion.previous_version.version), :method => :post, :id => "discussion-previous-version", :remote => true
      -else
        =link_to t("description_history.previous"), "#", :class => "disabled"
      =" | "
      -if @discussion.next_version.present?
        =link_to t("description_history.next"), preview_version_discussion_path(@discussion, @discussion.next_version.version), :method => :post, :id => "discussion-next-version", :remote => true
      -elsif !(@discussion.live?)
        =link_to t("description_history.next"), preview_version_discussion_path(@discussion), :method => :post, :remote => true
      -else
        =link_to t("description_history.next"), "#", :class => "disabled"
  .revision-content
    %p= render_rich_text(@discussion.description, @discussion.uses_markdown)
.modal-footer
  = link_to t(:close), "#", "data-dismiss" => "modal", class: "btn btn-small btn-grey"

app/views/discussions/_discussion_context.html.haml
.row
  .span8
    =render 'description', discussion: @discussion, description: @discussion.description, description_markdown_setting: @discussion.uses_markdown
  .span3.right-context
    .helper-text.discussion-description-helper-text.hidden
      =render "application/hint", text: t(:"hint.context"), anchor: 'starting-an-engaging-discussion'
    - if can?(:invite_people, @group)
      = icon_button(href: new_discussion_invitation_path(@discussion), text: t(:invite_people), icon: '/assets/member-18.png', id: 'invite-new-members', class: 'btn-grey')
    .discussion-additional-info
      = t("discussion_context.started_html",
          when: time_ago_in_words(@discussion.created_at),
          who: @discussion.author.name,
          link: user_path(@discussion.author),
          link_class: 'user-name')
      -if @discussion.originator.present?
        - last_collaborator = @discussion.last_collaborator
        .last-edited-by
          = t("discussion_context.last_edited_html",
              when: time_ago_in_words(@discussion.last_versioned_at),
              who: last_collaborator.name,
              link: user_path(last_collaborator),
              link_class: 'user-name')
        .see-revision-history
          %i.fa.fa-time
          =link_to t("discussion_context.see_revision_history"), show_description_history_discussion_path(@discussion), :method => :post, :class => "see-description-history", :remote => true
#description-revision-history.modal.hidden

app/views/discussions/_discussion_item.html.haml
.activity-item-body
  %div{:class => "activity-icon " + item.icon }
  %span.activity-item-actor
    - unless item.actor.blank?
      =link_to item.actor.name, user_path(item.actor), class: "user-name"
  %span.activity-item-header= item.header
  %span.activity-item-content.word-break= item.body
  .activity-item-time= t(:ago, :quantity_of_time => time_ago_in_words(item.time))

app/views/discussions/_discussion_list.html.haml
%section.span9#group-discussions
  %ul.selector-list.bordered
    #discussions-with-motions
      - @discussions_with_open_motions.each do |discussion|
        %li.selector-item= render '/discussions/discussion_preview', discussion: discussion
      - unless @discussions_with_open_motions.empty?
        .discussion-with-motion-divider
  %ul.selector-list
    #discussion-list
      - @discussions_without_open_motions.each do |discussion|
        %li.selector-item= render '/discussions/discussion_preview', discussion: discussion
  - if @group
    - if user_sees_private_discussions_message?(current_user, @group)
      = t :private_group_discussion_display
    - elsif @discussions_without_open_motions.empty? && @discussions_with_open_motions.empty?
      %li.empty-list-message= t :empty_discussion_index_group
  - else
    - if @discussions_with_open_motions.empty? and @discussions_without_open_motions.empty?
      %li.empty-list-message.hidden= t(:empty_discussion_index)

  = paginate @discussions_without_open_motions, :window => 3

app/views/discussions/_options.html.haml
.dropdown#discussion-options
  %a.dropdown-toggle{href:"#", id: "options-dropdown", 'data-toggle' => 'dropdown'}
    %i.fa.fa-cog
  %ul.dropdown-menu.pull-right
    - if can?(:edit, discussion)
      %li= link_to t(:edit_discussion), edit_discussion_path, class: 'edit-discussion'
    - if can?(:move, @discussion)
      %li= link_to t(:move_discussion), '#move-discussion-modal', "data-toggle" => "modal", id: 'move-discussion'
    -if can? :destroy, discussion
      %li= link_to t(:delete_discussion), "#", 'data-method-type' => 'delete', 'data-title' => t(:delete_discussion), 'data-body' => t(:confirm_delete_discussion), 'data-confirm-path' => discussion_path(discussion), class: 'confirm-dialog', id: 'delete-discussion'

- if can?(:move, @discussion)
  #move-discussion-modal.modal.hidden
    .modal-header
      %button.close{"data-dismiss" => "modal"}×
      %h3= t :move_discussion_where
    - destination_groups=  destinations_for(discussion: discussion, user: current_user)
    - hidden_destination_group_ids = destination_groups.select{|g| g.is_hidden?}.map(&:id)
    - private_int = @discussion.private ? 1 : 0
    = form_tag move_discussion_path(discussion), method: :post, data: {hidden_group_ids: hidden_destination_group_ids.join(' '), private_discussion: @discussion.private }, class: 'move-discussion-form' do
      .modal-body
        = select_tag :destination_group_id, options_for_select(destination_groups.map{|g| [g.name, g.id]})
      .warn-move-will-make-private{style: "display: none"}
        %i.fa.fa-lock
        = t(:move_discussion_to_hidden_group)
      .modal-footer
        = submit_tag t(:move_discussion), class: "btn btn-info", id: 'move-discussion-submit', :data => { :disable_with => "Move discussion" }
        = link_to "Cancel", "#", "data-dismiss" => "modal", class: "btn"

app/views/discussions/_prompt_logged_in_user_to_join_modal.html.haml
.modal.hide#prompt-user-to-join-or-authenticate
  .modal-header
    %h3= t :"prompt_user_to_join.header"
    %button.close{"data-dismiss" => "modal"}×
  .modal-body
    %p= t :"prompt_user_to_join.body"
  .modal-footer
    =link_to t(:ask_to_join_group), group_ask_to_join_path(@group), class: "btn btn-large btn-primary", id: "align-button"

= render 'discussions/js_prompt_user_to_join_or_authenticate'

app/views/discussions/_prompt_logged_out_user_to_authenticate_or_signup_modal.html.haml
.modal.hide#prompt-user-to-join-or-authenticate
  .modal-header
    %h3= t :"prompt_visitor_to_authenticate.header"
    %button.close{"data-dismiss" => "modal"}×
  .modal-body
    %p= t :"prompt_visitor_to_authenticate.body"
    %p= t :"prompt_user_to_join.body"
  .modal-footer
    =link_to t(:log_in), new_user_session_path, class: "btn btn-large btn-success"
    =link_to t(:ask_to_join_group), group_ask_to_join_path(@group), class: "btn btn-large btn-primary", id: "align-button"

= render 'discussions/js_prompt_user_to_join_or_authenticate'

app/views/discussions/add_comment.js.erb
$("#new-comment").val('');
$("ul#activity-list").append("<li class='activity-item-container'><%=escape_javascript(render @comment)%></li>");

$('.attachment-success').remove()
$('#new-comment-form').find("input[name='attachments[]']").remove()

app/views/discussions/new.html.haml
.page-container
  = render '/groups/title'
  %h2= t "discussion_form.new.header"

  = render "/discussions/form", :discussion => @discussion, :user_groups => @user_groups