config/routes.rb
Loomio::Application.routes.draw do

  slug_regex = /[a-z0-9\-\_]*/i
  ActiveAdmin.routes(self)

  namespace :admin do
    resource :email_groups, only: [:create, :new]
    resources :stats, only: [] do
      collection do
        get :events
      end
    end
  end

  get "/explore", to: 'explore#index', as: :explore
  get "/explore/search", to: "explore#search", as: :search_explore
  get "/explore/category/:id", to: "explore#category", as: :category_explore

  get "/groups", to: 'public_groups#index', as: :public_groups

  get "/new_group", to: 'groups#new'

  resource :search, only: :show

  devise_for :users, controllers: { sessions: 'users/sessions',
                                    registrations: 'users/registrations',
                                    omniauth_callbacks: 'users/omniauth_callbacks' }

  namespace :inbox do
    get   '/', action: 'index'
    get   'size'
    get   'preferences'
    put   'update_preferences'
    match 'mark_as_read'
    match 'mark_all_as_read/:id', action: 'mark_all_as_read', as: :mark_all_as_read
    match 'unfollow'
  end

  resources :group_requests, only: [:create, :new] do
    get :confirmation, on: :collection
  end

  resources :invitations, only: [:show, :create, :destroy]

  resources :groups, path: 'g', only: [:create, :edit] do
    scope module: :groups do
      resources :memberships, only: [:index, :destroy, :new, :create] do
        member do
         post :make_admin
         post :remove_admin
        end
      end
      resource :subscription, controller: 'subscriptions', only: [:new, :show] do
        collection do
          post :checkout
          get :confirm
          get :payment_failed
        end
      end
      scope controller: 'group_setup' do
        member do
          get :setup
          put :finish
        end
      end

      get :ask_to_join, controller: 'membership_requests', action: :new
      resources :membership_requests, only: [:create]
      get :membership_requests,  to: 'manage_membership_requests#index', as: 'membership_requests'
    end

    member do
      post :add_members
      post :hide_next_steps
      get :add_subgroup
      post :email_members
      post :edit_description
      delete :leave_group
      get :members_autocomplete
    end

    resources :motions,     only: [:index]
    resources :discussions, only: [:index, :new]
    resources :invitations, only: [:new, :destroy]
  end

  scope module: :groups, path: 'g', slug: slug_regex do
    get    ':id(/:slug)', action: 'show', as: :group
    put    ':id(/:slug)', action: 'update'
    delete ':id(/:slug)', action: 'destroy'

    post 'archive/:id',  action: 'archive', as: :archive_group
  end

  scope module: :groups do
    resources :manage_membership_requests, only: [], as: 'membership_requests' do
      member do
        post :approve
        post :ignore
      end
    end
  end
  delete 'membership_requests/:id/cancel', to: 'groups/membership_requests#cancel', as: :cancel_membership_request

  resources :motions, path: 'm', only: [:new, :create, :edit, :index] do
    resources :votes, only: [:new, :create, :update]
    member do
      put :close
      put :create_outcome
      post :update_outcome
      put :edit_close_date
    end
  end

  scope module: :motions, path: 'm', slug: slug_regex do
    get    ':id(/:slug)', action: 'show', as: :motion
    put    ':id(/:slug)', action: 'update'
    delete ':id(/:slug)', action: 'destroy'
  end

  resources :discussions, path: 'd', only: [:new, :edit, :create] do
    get :activity_counts, on: :collection
    resources :invitations, only: [:new]

    member do
      post :update_description
      post :update
      post :add_comment
      post :show_description_history
      get :new_proposal
      post :move
    end
  end

  scope module: :discussions, path: 'd', slug: slug_regex do
    get    ':id(/:slug)', action: 'show',    as: :discussion
    put    ':id(/:slug)', action: 'update'
    delete ':id(/:slug)', action: 'destroy'

    post ':id/preview_version/(:version_id)', action: 'preview_version', as: 'preview_version_discussion'
    post 'update_version/:version_id',        action: 'update_version',   as: 'update_version_discussion'
  end

  resources :comments , only: :destroy do
    post :like, on: :member
    post :translate, on: :member
  end

  resources :attachments, only: [:create, :new] do
    collection do
      get 'sign'
      get :iframe_upload_result
    end
  end

  resources :notifications, :only => :index do
    collection do
      get :groups_tree_dropdown
      get :dropdown_items
      post :mark_as_viewed
    end
  end

  resources :users, path: 'u', only: [:new] do
    member do
      put :set_avatar_kind
      post :upload_new_avatar
    end
  end

  scope module: :users do
    match '/profile',          action: 'profile', as: :profile
    scope module: :email_preferences do
      get '/email_preferences', action: 'edit',   as: :email_preferences
      put '/email_preferences', action: 'update', as: :update_email_preferences
    end
  end

  scope module: :users, path: 'u' do
    get ':id(/:slug)', action: 'show',    slug: slug_regex, as: :user
    put ':id(/:slug)', action: 'update',  slug: slug_regex
  end

  match '/announcements/:id/hide', to: 'announcements#hide', as: 'hide_announcement'

  get '/users/invitation/accept' => redirect {|params, request|  "/invitations/#{request.query_string.gsub('invitation_token=','')}"}
  get '/group_requests/:id/start_new_group' => redirect {|params, request|  "/invitations/#{request.query_string.gsub('token=','')}"}

  get '/contributions' => redirect('/crowd')
  get '/contributions/thanks' => redirect('/crowd')
  get '/contributions/callback' => redirect('/crowd')
  get '/crowd' => redirect('https://love.loomio.org/')

  # resources :contributions, only: [:index, :create] do
  #   get :callback, on: :collection
  #   get :thanks, on: :collection
  # end

  get '/dashboard', to: 'dashboard#show', as: 'dashboard'
  root :to => 'marketing#index'

  scope controller: 'pages' do
    get :about
    get :privacy
    get :purpose
    get :services
    get :terms_of_service
    get :third_parties
    get :wallets
    get :browser_not_supported
  end

  scope controller: 'campaigns' do
    get :hide_crowdfunding_banner
  end

  scope controller: 'help' do
    get :help
  end

  get '/detect_locale' => 'detect_locale#show'
  match '/detect_video_locale' => 'detect_locale#video', as: :detect_video_locale

  resources :contact_messages, only: [:new, :create]
  match 'contact(/:destination)', to: 'contact_messages#new'

  #redirect from wall to new group signup
  namespace :group_requests do
    get 'selection', action: 'new'
    get 'subscription', action: 'new'
    get 'pwyc', action: 'new'
  end

  #redirect old invites
  match "/groups/:id/invitations/:token" => "group_requests#start_new_group"

  #redirect old pages:
  get '/we_the_people' => redirect('/')
  get '/collaborate'   => redirect('/')
  get '/woc'           => redirect('/')
  get '/discussions/:id', to: 'discussions_redirect#show'
  get '/groups/:id',      to: 'groups_redirect#show'
  get '/motions/:id',     to: 'motions_redirect#show'

  scope path: 'pages' do
    get 'home'         => redirect('/')
    get 'how*it*works' => redirect('/purpose#how-it-works')
    get 'get*involved' => redirect('/about')
    get 'privacy'      => redirect('/privacy_policy')
    get 'about'        => redirect('/about#about-us')
    match 'contact'    => 'contact_messages#new'
  end

  get '/get*involved'       => redirect('/purpose#how-it-works')
  get '/how*it*works'       => redirect('/purpose#how-it-works')
  get '/about#how-it-works' => redirect('/purpose#how-it-works')

  get '/blog'       => redirect('http://blog.loomio.org')
  get '/press'      => redirect('http://blog.loomio.org/press-pack')
  get '/press-pack' => redirect('http://blog.loomio.org/press-pack')
end

app/controllers/groups/group_setup_controller.rb
class Groups::GroupSetupController < GroupBaseController

  before_filter :require_current_user_is_group_admin
  before_filter :redirect_to_group_if_already_setup

  def setup
  end

  def finish
    if @group.update_attributes(permitted_params.group)
      @group.mark_as_setup!
      InvitePeopleMailer.delay.welcome(@group)
      redirect_to @group
    else
      render 'setup'
    end
  end

  private

  def redirect_to_group_if_already_setup
    if @group.is_setup?
      flash[:warning] = t("error.group_already_setup")
      redirect_to @group
    end
  end
end

app/controllers/groups/manage_membership_requests_controller.rb
class Groups::ManageMembershipRequestsController < GroupBaseController
  load_and_authorize_resource :membership_request, only: [:approve, :ignore], parent: false
  before_filter :load_group_and_check_for_response, only: [:approve, :ignore]

  def index
    @group = GroupDecorator.new Group.find(params[:group_id])
    if can? :manage_membership_requests, @group
      render 'index'
    else
      redirect_to group_path(@group)
      flash[:warning] = t(:'error.access_denied')
    end
  end

  def approve
    ManageMembershipRequests.approve!(@membership_request, approved_by: current_user)
    set_request_approved_flash_message
    redirect_to group_membership_requests_path(@group)
  end

  def ignore
    ManageMembershipRequests.ignore!(@membership_request, ignored_by: current_user)
    flash[:success] = t(:'notice.membership_request_ignored')
    redirect_to group_membership_requests_path(@group)
  end

  private

  def load_group_and_check_for_response
    @group = @membership_request.group
    response = @membership_request.response
    unless response.nil?
      if response == 'approved'
        flash[:warning] = t(:'warning.membership_request_already_approved')
      elsif response == 'ignored'
        flash[:warning] = t(:'warning.membership_request_already_ignored')
      end
      redirect_to group_membership_requests_path(@group)
    end
  end

  def set_request_approved_flash_message
    if @membership_request.from_a_visitor?
      flash[:success] = t(:'notice.membership_approved')+ ' ' +  t(:'notice.new_user_added', user_email_or_name: @membership_request.name)
    else
      flash[:success] = t(:'notice.membership_approved')+ ' ' + t(:'notice.user_added', user_email_or_name: @membership_request.name)
    end
  end
end

app/controllers/groups/membership_requests_controller.rb
class Groups::MembershipRequestsController < BaseController
  before_filter :load_group, except:[:cancel]
  skip_before_filter :authenticate_user!, except: :cancel
  load_and_authorize_resource :membership_request, only: :cancel, parent: false


  def new
    authorize! :request_membership, @group
    @membership_request = MembershipRequest.new
    @membership_request.group = @group
    @membership_request.requestor = current_user
    store_referer_location
  end

  def create
    authorize! :request_membership, @group
    build_membership_request

    if @membership_request.persisted?
      flash[:success] = t(:'success.membership_requested', which_group: @group.full_name)
      redirect_to after_request_membership_path
    else
      if @membership_request.errors[:requestor].any?
        flash[:warning] = @membership_request.errors[:requestor].first
        redirect_to @group
      else
        render 'new'
      end
    end
  end

  def cancel
    @membership_request.destroy
    flash[:success] = t(:'notice.membership_request_canceled')
    redirect_to @membership_request.group
  end

  private

  def store_referer_location
    session['user_return_to'] = request.env['HTTP_REFERER']
  end

  def after_request_membership_path
    path = session['user_return_to'] || group_path(@group)
    clear_stored_location
    path
  end

  def build_membership_request
    @membership_request = RequestMembership.to_group(
                            params: permitted_params.membership_request,
                            requestor: current_user,
                            group: @group)
  end

  def load_group
    @group ||= GroupDecorator.new Group.find_by_key!(params[:group_id])
  end
end

app/helpers/groups_helper.rb
module GroupsHelper

  def css_for_privacy_link(group, link)
    current_privacy_setting = String(group.privacy)
    return "icon-ok" if link == current_privacy_setting
  end

  def display_subgroups_block?(group)
    group.parent.nil? && (group.subgroups.present? || (current_user && group.users_include?(current_user)))
  end

  def show_next_steps?(group)
    user_signed_in? && current_user.is_group_admin?(group) && !group.next_steps_completed? && @group.is_top_level?
  end

  def show_subscription_prompt?(group)
    user_signed_in? && current_user.is_group_admin?(group) &&
      ( group.created_at < 1.month.ago ) &&
      !group.has_subscription_plan? &&
      !group.has_manual_subscription? &&
      !group.is_a_subgroup?
  end

  def pending_membership_requests_count(group)
    if group.pending_membership_requests.count > 0
      t(:number_pending, pending: group.pending_membership_requests.count)
    else
      ""
    end
  end

  def members_pending_count(group)
    if group.pending_invitations.count > 0
      t(:and_number_pending, pending: group.pending_invitations.count)
    else
      ""
    end
  end

  def request_membership_button(group)
    if visitor?
      request_membership_icon_button(group)
    else
      return if group.users_include?(current_user)

      membership_request = group.membership_requests.pending.requested_by(current_user).first
      if membership_request.present?
        cancel_membership_request_button(membership_request)
      else
        request_membership_icon_button(group)
      end
    end
  end

  def disabled_request_membership_button(group)
    request_membership_icon_button(group, href: "#", class: "btn-info disabled tooltip-top",
                                   id: 'request-membership-disabled',
                                   title: "You must be a member of the parent group before you can join this subgroup.")
  end

  def cancel_membership_request_button(membership_request)
    icon_button(href: cancel_membership_request_path(membership_request),
                method: 'delete',
                text: t(:cancel_membership_request),
                icon: '/assets/group-dark.png',
                id: 'membership-requested',
                class: 'btn-grey',
                'data-confirm' => t(:confirm_remove_membership_request))
  end

  def request_membership_icon_button(group, params={})
    old_params = { href: group_ask_to_join_path(group),
                   text: t(:ask_to_join_group),
                   icon: nil,
                   id: 'request-membership',
                   class: 'btn-info' }
    new_params = old_params.merge(params)
    icon_button(new_params)
  end

  def group_privacy_options(group)
    privacy_settings = []
    Group::PRIVACY_CATEGORIES.each do |privacy_setting|
      header = t "simple_form.labels.group.privacy_#{privacy_setting}_header"
      description = t "simple_form.labels.group.privacy_#{privacy_setting}_description"

      if privacy_setting != 'hidden' && group.is_a_subgroup? && group.parent.privacy == 'hidden'
        disabled_class = 'disabled'
        text_color = '#CCCCCC'
      else
        disabled_class = ''
        text_color = ''
      end
      privacy_settings << ["<span class='privacy-setting-header #{disabled_class}'>#{header}</strong><br />
                            <p style='color:#{text_color}'>#{description}</p>".html_safe, privacy_setting.to_sym]
    end
    privacy_settings
  end

  def group_privacy_options_disabled(group)
    if group.is_a_subgroup? && group.parent.privacy == 'hidden'
      ['public', 'private']
    else
      []
    end
  end

  def group_viewable_by_parent_label(group)
    t(:'simple_form.labels.group.viewable_by_parent_members_header', group: group.parent.name)
  end

  def group_invitable_by_options(group)
    [[t('simple_form.labels.group.members_invitable_by_coordinators'), :admins],
     [t('simple_form.labels.group.members_invitable_by_members'), :members]]
  end

  def user_sees_private_discussions_message?(user, group)
    group.privacy == 'private' &&
    group.members.exclude?(user) &&
    group.discussions.where('private = ?', false).empty?
  end

end

app/views/groups/_email_members.html.haml
.modal-header
  %button.close{"data-dismiss" => "modal"}×
  %h3= t :email_members_in_group, which_group: group.full_name
= form_tag email_members_group_path(group) do
  .modal-body
    .control-group
      = label_tag "group_email_subject", t(:subject)
      %span.presence-error-message= t :subject_error
      = text_field_tag "group_email_subject", nil, :placeholder => t(:subject_placeholder), :class => "validate-presence"
    .control-group
      = label_tag "group_email_body", t(:message)
      %span.presence-error-message= t :message_error
      = text_area_tag "group_email_body", nil, :placeholder => t(:message_placeholder, which_group: group.full_name), :class => "validate-presence"
  .modal-footer
    = submit_tag t(:send_email), class: "btn btn-info run-validations", :data => { :disable_with => t(:send_email) }

app/views/groups/_form.html.haml
- form_params ||= {}
- form_params.merge!({validate: true, html: {'data-current-privacy' => group.privacy}})
- privacy_options = group_privacy_options(group)
- privacy_options_disabled = group_privacy_options_disabled(group)

= simple_form_for group, form_params do |f|
  = f.input :name, label: false
  = f.input :description, as: :text, label: false
  = f.input :privacy, :as => 'radio_buttons', collection: privacy_options, disabled: privacy_options_disabled
  - if group.is_a_subgroup?
    = f.input :viewable_by_parent_members, inline_label: group_viewable_by_parent_label(group), label: false

  = f.input :members_invitable_by, :as => "radio_buttons", collection: group_invitable_by_options(group)
  = f.input :parent_id, :as => :hidden, :input_html => { :value => group.parent.id } if group.parent
  = f.submit submit_text, class: 'btn btn-info btn-large', id: 'group_form_submit', :data => { :disable_with => submit_text }

app/views/groups/_group_admin_panel.html.haml
.sub-panel#group-admin-panel
  %h4 Admin
  %ul
    %li=link_to 'Edit memberships', group_memberships_path(group)
    %li=link_to 'Pending invitations', group_invitations_path(group)

app/views/groups/_members.html.haml
- unless group.hide_members && (cannot? :update, group)
  .sub-panel#members-panel
    %h4
      = link_to group_memberships_path(group) do
        = t :members
        = "(#{ group.memberships_count })"

    %ul#users-list.clearfix
      - group.members.first(15).each do |user|
        %li{:id => user.id}
          = render 'linked_avatar', user: user, show_title: true
    %div.memberships_link
      = link_to t(:more), group_memberships_path(group), class: 'bottom-panel-link'

app/views/groups/_membership_request.html.haml
%li
  .membership-user-name= truncate(membership_request.name, :length => 29, :omission => '...')
  =link_to t(:approve), "#", 'data-title' => t(:approve), 'data-body' => t(:confirm_approve_membership_request, which_user: membership_request.name), 'data-confirm-path' => approve_membership_request_path(membership_request), 'data-method-type' => 'post', class: 'confirm-dialog', id: 'approve'
  =link_to "×", "#", 'data-title' => t(:ignore_request), 'data-body' => t(:confirm_ignore_membership_request, which_user: membership_request.name), 'data-confirm-path' => ignore_membership_request_path(membership_request), 'data-method-type' => 'post', class: 'confirm-dialog close', id: 'ignore'

app/views/groups/_membership_requests.html.haml
- if group.membership_requests.where(response: nil).exists? && (can? :add_members, group)

  .sub-panel#user-requests
    %h4= t(:membership_requests)
    / # - group.membership_requests.where(response: nil).each do |request|
    / #   = render 'membership_request', membership_request: request
    = link_to pending_membership_requests_count(group), group_membership_requests_path(group), class: 'bottom-panel-link', id: 'pending-count'

app/views/groups/_options_dropdown.html.haml
- if params[:controller] == 'groups' && params[:action] == 'show'
  - can_edit = can? :edit, group
  - can_leave = group.users_include? current_user
  - can_archive = can? :edit, group
  - can_email = can? :email_members, group
  - if can_edit || can_leave
    .dropdown.group-options
      = icon_button(href: '#', text: t(:options), icon: '/assets/options-cog.png', id: 'group-options', class: 'btn-grey dropdown-toggle', 'data-toggle' => 'dropdown')
      %ul.dropdown-menu.pull-right
        - if can_edit
          %li= link_to t(:edit_group_settings), edit_group_path(group)
        / - if (can? :view_payment_details, group)
        /   %li= link_to t(:group_subscription), group_subscription_path(group)
        - if can_leave
          - membership = current_user.group_membership(group)
          - if @group.is_hidden?
            - msg = t(:confirm_leave_hidden_group, which_group: group.name)
          - else
            - msg = t(:confirm_leave_group, which_group: group.name)
          %li= link_to t(:leave_group), "#", 'data-title' => t(:leave_group), 'data-body' => msg, 'data-confirm-path' => group_membership_path(group, membership), 'data-method-type' => 'delete', class: 'confirm-dialog', id: 'leave group'
        - if can_archive
          %li= link_to t(:deactivate_group), "#", 'data-title' => t(:deactivate_group), 'data-body' => t(:confirm_deactivate_group, which_group: group.name), 'data-confirm-path' => archive_group_path(group), 'data-method-type' => 'post', class: 'confirm-dialog', id: 'de-activate group'
  - if can_email
    #email-members-modal.modal.hidden
      = render "groups/email_members", :group => group

app/views/groups/_setup_next_steps.html.haml
.sub-panel#setup-next-steps
  %h4
    = t :setup_steps_title
    = link_to("×", hide_next_steps_group_path(@group), method: :post, remote: true, class: "close hide-next-steps")
  %ol
    %li#example_discussion= t(:setup_step_1)
    %li#first_discussion= t(:setup_step_2)
    %li#invite_people= t(:setup_step_3)

app/views/groups/_subscription_prompt.html.haml
.sub-panel#subscription_prompt
 %h4
  %span.heart-icon ❤
  Pay what you can
 %p Your group has not yet chosen a subscription. You can choose whatever is right for your group, even $0!
 %p
  = link_to "Set up your subscription", group_subscription_path(@group), class: 'bottom-panel-link'

app/views/groups/edit.html.haml
- set_title @group.name, t(:edit_group)
= render '/groups/title', group: @group
.row
  .span6
    %h2= t :edit_group
    = render 'form', group: @group, parent: @parent, submit_text: t(:update_group)

app/views/groups/edit_description.js.erb
$(".long-description").html("<%= j render_rich_text(@description, false) %>")
$(".description-body").show()
$("#description-edit-form").hide()
$(".discussion-description-helper-text").toggle()

app/views/groups/hide_next_steps.js.erb
$('#setup-next-steps').hide();

app/views/groups/new.html.haml
.row
  .span6
    #intro
      %h1 Start your group
      = render 'form', group: @group, submit_text: t(:start_group)

app/views/groups/show.html.haml
.row
  .span9
    - set_title @group.name, "", @group.parent
    = render '/groups/title', group: @group, discussion: @discussion
    - if can? :create, @discussion
      = icon_button(href: new_discussion_path(:group_id => @group.id), text: t(:start_a_discussion), icon: '/assets/topic-18.png', id: 'start-new-discussion', class: 'btn-grey')
  .span3#button-container
    - if can?(:add_members, @group)
      = render 'invite_button', group: @group, discussion: @discussion
    = render 'options_dropdown', group: @group
    = request_membership_button(@group)

.row.main-content
  =render 'discussions/discussion_list'
  %section.span3
    =render 'setup_next_steps' if show_next_steps?(@group)
    / =render 'subscription_prompt' if show_subscription_prompt?(@group)
    =render 'groups/description', group: @group
    =render 'subgroups', subgroups: @subgroups, group: @group if display_subgroups_block?(@group)
    - if can? :show, @group
      - if @closed_motions.exists?
        .sub-panel.previous-discussions-panel
          %h4= t(:previous_decisions)
          %ul.previous-decisions
            - @closed_motions.first(3).each do |motion|
              %li.previous-decision
                %a.selector-link{ href: motion_path(motion) }
                  .clearfix
                    .pie.motion-sparkline
                      -values = motion.vote_counts.values
                      -if values.sum == 0
                        0,0,0,0,1
                      -else
                        =values.join(',')
                    .previous-decision-title.word-break=truncate(motion.name, :length => 60, :separator => ' ')

          = link_to t(:see_more), group_motions_path(@group), class: 'bottom-panel-link'
    =render 'membership_requests', group: @group
    =render 'members', group: @group
  =render '/application/closed_motions', user: nil, group: @group